django_paradox_mode_translation/chats/urls.py
from django.urls import path

from chats.views import SendMessageView

app_name = 'chats'

urlpatterns = [
    path('<slug:slug>/', SendMessageView.as_view(), name='send_message')
]

django_paradox_mode_translation/django_paradox_mode_translation/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django_paradox_mode_translation import settings

urlpatterns = [
    path('', include('translators_hub.urls'), name='home'),
    path('teams/', include('teams.urls'), name='teams'),
    path('moderators/', include('moderators.urls'), name='moderators'),
    path('chats/', include('chats.urls'), name='chats'),
    path('admin/', admin.site.urls),

]

if settings.DEBUG is True:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

django_paradox_mode_translation/teams/urls.py
from django.urls import path

from teams import views

app_name = 'teams'

urlpatterns = [
    path('', views.TeamsView.as_view(), name='home'),
    path('create-team/', views.CreateTeamView.as_view(), name='create_team'),
    path('invites/', views.TeamInvitesHandler.as_view(), name='invites'),
    path('search-team/', views.SearchTeamView.as_view(), name='search_team'),
    path('<slug:slug>/', views.TeamPageView.as_view(), name='team_detail'),
    path('<slug:slug>/invite-users/', views.SendInviteView.as_view(), name='invite_user'),
]

django_paradox_mode_translation/teams/models.py
from django.db import models
from django.urls import reverse


class Teams(models.Model):
    team_title = models.CharField(
        max_length=120,
        unique=True,
        verbose_name="Название команды"
    )

    slug = models.SlugField(
        db_index=True,
        unique=True,
        verbose_name="URL"
    )

    description = models.CharField(
        max_length=1000,
        blank=True,
        null=True,
        verbose_name='Описание'
    )

    reputation = models.IntegerField(
        default=0,
        verbose_name='Репутация'
    )

    is_open = models.BooleanField(
        blank=False,
        default=True,
        null=False,
        verbose_name="Открыт набор"
    )

    def get_absolute_url(self):
        return reverse('teams:team_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'Команда {self.team_title}'

    class Meta:
        verbose_name = "Команда"
        verbose_name_plural = "Команды"


class TeamMembers(models.Model):
    CREATOR = True
    MEMBER = None

    ROLES = [
        (CREATOR, 'Создатель'),
        (MEMBER, 'Член команды')
    ]

    team = models.ForeignKey(to=Teams, on_delete=models.CASCADE, related_name='team_members', verbose_name='Команда')

    user = models.ForeignKey(to='auth_app.User', on_delete=models.CASCADE, related_name='membership')

    role = models.BooleanField(blank=True, default=None, null=True, choices=ROLES, verbose_name="Роль в команде")

    def __str__(self):
        return f'Член команды {self.team} - {self.user}, роль - {self.get_role_display()}'

    class Meta:
        verbose_name = "Член команды"
        verbose_name_plural = "Члены команды"


class TeamInvites(models.Model):
    NO_RESPONSE = 'no_resp'
    ACCEPTED = 'ok'
    DECLINED = 'no'
    STATUS = [
        (NO_RESPONSE, 'Нет ответа'),
        (ACCEPTED, 'Принято'),
        (DECLINED, 'Отклонено')
    ]

    team = models.ForeignKey(
        to=Teams,
        on_delete=models.CASCADE,
    )

    sender = models.ForeignKey(
        to='auth_app.User',
        on_delete=models.CASCADE,
        related_name='team_sender_name'
    )

    target = models.ForeignKey(
        to='auth_app.User',
        on_delete=models.CASCADE,
        related_name='team_target_name'
    )

    text_invite = models.CharField(
        max_length=500,
        blank=True,
    )

    status = models.CharField(
        max_length=7,
        choices=STATUS,
        blank=False,
        null=False,
        default=None,
    )

    def __str__(self):
        return f'Приглашение для {self.target}, в команду {self.team}'

    class Meta:
        verbose_name = "Приглашение"
        verbose_name_plural = "Приглашения"

django_paradox_mode_translation/teams/forms.py
from django import forms

from teams.models import TeamInvites, Teams, TeamMembers


class CreateTeamForm(forms.ModelForm):

    team_title = forms.CharField(
        widget=forms.TextInput(attrs={

        }),
        label="Название команды",
    )

    description = forms.CharField(
        widget=forms.Textarea(attrs={

        }),
        required=False,
        label="Описание"
    )

    def save(self, user=None, commit=True):
        instance = super(CreateTeamForm, self).save(commit)
        if user:
            team_member, created = TeamMembers.objects.get_or_create(team=instance, user=user)
            if created:
                team_member.role = TeamMembers.CREATOR
                team_member.save()
        return instance

    class Meta:
        model = Teams
        fields = ['team_title', 'description']


class InviteUserForm(forms.ModelForm):

    text_invite = forms.CharField(
        max_length=500,
        label='Приглашение',
        required=False,
        widget=forms.Textarea(attrs={
            'rows': 10,
            'col': 50
        })
    )

    class Meta:
        model = TeamInvites
        fields = ['text_invite']


class SearchTeamForm(forms.Form):

    search_str = forms.CharField(
        widget=forms.TextInput(attrs={

        }),
        label="Поиск"
    )

    is_open = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={

        }),
        required=False,
        label="Происходит набор"
    )

django_paradox_mode_translation/teams/views.py
from django.contrib import messages
from django.contrib.postgres.search import SearchVector
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse
from django.views import generic

from teams.forms import InviteUserForm, CreateTeamForm, SearchTeamForm
from teams.models import Teams, TeamInvites, TeamMembers
from auth_app.models import User

from slugify import slugify

from translators_hub.utils.custom_paginator import CustomPaginator


class TeamsView(generic.ListView):
    template_name = 'teams/home.html'
    context_object_name = 'teams'

    def get_queryset(self):
        teams = self.request.user.membership.all()
        queryset = Teams.objects.filter(team_members__in=teams).prefetch_related('team_members')
        return queryset

    def get(self, request, *args, **kwargs):
        return super(TeamsView, self).get(request, *args, **kwargs)


class TeamPageView(generic.DetailView):
    model = Teams
    template_name = 'teams/team_page.html'
    context_object_name = 'team_data'

    def get_object(self, queryset=None):
        obj = self.model.objects.filter(slug=self.kwargs.get('slug')).prefetch_related('team_members__user')[0]
        return obj

    def get(self, request, *args, **kwargs):
        return super(TeamPageView, self).get(request, *args, **kwargs)


class CreateTeamView(generic.FormView):
    form_class = CreateTeamForm
    template_name = 'teams/create_team.html'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.instance.slug = slugify(form.instance.team_title)
            form.save(request.user)
            return redirect('teams:home')
        else:
            return self.form_invalid(form)


class SendInviteView(generic.ListView):
    template_name = 'teams/invite_user.html'
    context_object_name = 'free_users'

    def get_queryset(self):
        team = Teams.objects.get(slug=self.kwargs.get('slug'))
        free_users = User.objects.exclude(
            Q(membership__team=team) | Q(team_target_name__status=TeamInvites.NO_RESPONSE))
        return free_users

    def get(self, request, *args, **kwargs):
        form = InviteUserForm()
        self.extra_context = {'form': form, 'slug': kwargs.get('slug')}
        return super(SendInviteView, self).get(request, *args, **kwargs)

    def post(self, request, slug, *args, **kwargs):
        form = InviteUserForm(request.POST)
        data = form.save(commit=False)
        data.sender = request.user
        data.target_id = request.POST.get('target_user_id')
        data.team = Teams.objects.get(slug=slug)
        data.status = TeamInvites.NO_RESPONSE
        data.save()
        form.save_m2m()
        return redirect(reverse('teams:invite_user', kwargs={'slug': slug}))


class TeamInvitesHandler(generic.View):

    def post(self, request, *args, **kwargs):
        accepted = request.POST.get('accept')
        declined = request.POST.get('decline')
        if accepted:
            invites = TeamInvites.objects.filter(Q(pk__in=accepted) | Q(pk=accepted))
            for invite in invites:
                member_note = TeamMembers.objects.get_or_create(team=invite.team, user=request.user)[0]
                member_note.save()
                invite.status = TeamInvites.ACCEPTED
                invite.save()
        elif declined:
            invites = TeamInvites.objects.filter(pk=declined)
            for invite in invites:
                invite.status = TeamInvites.DECLINED
                invite.save()
        else:
            error_message = "Ошибка чтения значения кнопки, повторите попытку"
            messages.add_message(request=request, level=messages.ERROR, message=error_message)
        return redirect(reverse('translators_hub:invites', kwargs={'slug': request.user.userprofile.slug}))


class SearchTeamView(generic.edit.FormMixin, generic.ListView):
    template_name = 'teams/search_team.html'
    context_object_name = 'teams'
    paginate_by = 15
    paginator_class = CustomPaginator

    form_class = SearchTeamForm

    def get_queryset(self):
        search_vector = SearchVector('team_title', 'description')
        search_str = self.request.GET.get('search_str')
        filters = ~Q(team_members__user=self.request.user)
        if search_str:
            filters &= Q(search=search_str)
        if self.request.GET.get('is_open'):
            filters &= Q(is_open=True)
        teams = Teams.objects.annotate(search=search_vector).filter(filters).prefetch_related('team_members')
        return teams

    def get(self, request, *args, **kwargs):
        self.initial = request.GET
        form = self.get_form()
        self.extra_context = {'form': form}
        return super(SearchTeamView, self).get(request, *args, **kwargs)

django_paradox_mode_translation/teams/templates/teams/create_team.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Создать</button>
    </form>
{% endblock %}

django_paradox_mode_translation/teams/templates/teams/home.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    <a href="{% url 'teams:create_team' %}">Создать команду</a>

    <a href="{% url 'teams:search_team' %}">Найти команду</a>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Мои команды
                    </div>
                    <div class="card-body">
                        <ul>
                            {% for team in teams %}
                                <li>
                                    <a href="{{ team.get_absolute_url }}">
                                        <div class="card mb-3" style="cursor: pointer;">
                                            <div class="card-body">
                                                <h5 class="card-title">{{ team }}</h5>
                                                <p class="card-text">Количество участников: {{ team.team_members.all.count }}</p>
                                                <p class="card-text">{{ team.reputation }}</p>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

django_paradox_mode_translation/teams/templates/teams/invite_user.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    {% if free_users %}
        <div class="container">
            <table class="table table-bordered table-hover table-light">
                <tr>
                    <th>Ник</th>
                    <th>Почта</th>
                    <th>Описание</th>
                    <th>Титулы</th>
                </tr>
                {% for user in free_users %}
                    <tr>
                        <td><img src="/media/{{ user.userprofile.profile_image }}" class="profile-icon" alt="">{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.userprofile.description }}</td>
                        <td>{% if user.userprofile.titles.all %}{{ user.userprofile.titles.all }}{% else %}
                            ----{% endif %}</td>
                        <td>
                            <form method="post" action="{% url 'teams:invite_user' slug %}"
                                  id="{{ user }}">
                                {% csrf_token %}
                                <table class="table table-sm">
                                    {{ form }}
                                </table>
                                <input type="hidden" value="{{ user.pk }}" name="target_user_id">
                                <input type="hidden" value="{{ team_id }}" name="team_id">
                            </form>
                        </td>
                        <td>
                            <button class="btn btn-success" type="submit" form="{{ user }}">Пригласить</button>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <h1>Нет доступных кандидатов</h1>
    {% endif %}
{% endblock content %}

django_paradox_mode_translation/teams/templates/teams/search_team.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    <form method="get">
        {{ form }}
        <button type="submit">Поиск</button>
    </form>

    {% for team in teams %}
        {{ team.team_title }}
        {{ team.team_members.all|length }}
    {% endfor %}
{% endblock %}

django_paradox_mode_translation/teams/templates/teams/team_page.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    <div class="py-3"><a class="btn btn-success" href="{% url 'teams:invite_user' slug=team_data.slug %}">Пригласить в команду</a></div>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        {{ team_data.team_title }}
                    </div>
                    <div class="card-body">
                        <p>Здесь будет общая информация.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Пользователи
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">

                            <thead>
                            <tr>
                                <th>Имя человека</th>
                                <th>Должность</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for member in team_data.team_members.all %}
                            <tr>
                                <td>{{ member.user }}</td>
                                <td>{{ member.get_role_display }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}