django_paradox_mode_translation/chats/urls.py
from django.urls import path

from chats.views import SendMessageView

app_name = 'chats'

urlpatterns = [
    path('<slug:slug>/', SendMessageView.as_view(), name='send_message')
]

django_paradox_mode_translation/django_paradox_mode_translation/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django_paradox_mode_translation import settings

urlpatterns = [
    path('', include('translators_hub.urls'), name='home'),
    path('teams/', include('teams.urls'), name='teams'),
    path('moderators/', include('moderators.urls'), name='moderators'),
    path('chats/', include('chats.urls'), name='chats'),
    path('admin/', admin.site.urls),

]

if settings.DEBUG is True:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

django_paradox_mode_translation/moderators/urls.py
from django.urls import path

from moderators.views import ModeratorHomeView, SendQueryView, MyQueriesView, QueryBookingView, QueriesInWorkView, \
    QueryDetailView, AddGameView

app_name = 'moderators'

urlpatterns = [
    path('', ModeratorHomeView.as_view(), name='home'),
    path('send-query/', SendQueryView.as_view(), name='send_query'),
    path('my-queries/', MyQueriesView.as_view(), name='my_queries'),
    path('query-booking/', QueryBookingView.as_view(), name='query_booking'),
    path('queries-in-work/', QueriesInWorkView.as_view(), name='queries_in_work'),
    path('query<int:pk>', QueryDetailView.as_view(), name='query_detail'),
    path('add-game/', AddGameView.as_view(), name='add_game'),
]

django_paradox_mode_translation/teams/urls.py
from django.urls import path

from teams import views

app_name = 'teams'

urlpatterns = [
    path('', views.TeamsView.as_view(), name='home'),
    path('create-team/', views.CreateTeamView.as_view(), name='create_team'),
    path('invites/', views.TeamInvitesHandler.as_view(), name='invites'),
    path('search-team/', views.SearchTeamView.as_view(), name='search_team'),
    path('<slug:slug>/', views.TeamPageView.as_view(), name='team_detail'),
    path('<slug:slug>/invite-users/', views.SendInviteView.as_view(), name='invite_user'),
]

django_paradox_mode_translation/translators_hub/urls.py
from django.urls import path, include

from django_paradox_mode_translation import settings
from . import views
from django.conf.urls.static import static

app_name = 'translators_hub'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    # path('profile/<slug:slug>/', views.ProfileView.as_view(), name='profile'),
    # path('profile/<slug:slug>/update-profile/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('profile/<slug:slug>/invites/', views.InvitesView.as_view(), name='invites'),
    path('profile/<slug:slug>/my_projects/', views.MyProjectsView.as_view(), name='my_projects'),
    path('login/', views.LogInView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    # path('registration/', views.RegistrationView.as_view(), name='registration'),
    # path('add-page/', views.AddPageView.as_view(), name='add_page'),
    path('mods-translation/search/', views.SearchProjectView.as_view(), name='search'),
    # path('mods-translations/<slug:slug>/', views.DetailView.as_view(), name='detail_page'),
    # path('mods-translations/<slug:slug>/management/', views.ManagementView.as_view(), name='management'),
    # path('mods-translations/<slug:slug>/management/change_role/username=<str:username>', views.ChangeRoleView.as_view(), name='change_role'),
    # path('mods-translations/<slug:slug>/apply-for/', views.ApplyForView.as_view(), name='apply_for'),
    # path('mods-translations/<slug:slug>/invite_authors/', views.SendInvitesView.as_view(), name='invite_authors'),
    # path('like-comment/', views.like_comment, name='like-comment'),
    # path('dislike-comment/', views.dislike_comment, name='dislike-comment'),
]

django_paradox_mode_translation/translators_hub/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from channels_redis.core import RedisChannelLayer
from django.contrib.auth import views, login, authenticate, get_user_model
from django.contrib.auth.models import AnonymousUser
from django.contrib import messages
from django.contrib.postgres.search import SearchVector
from django.db.models import Q, F
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from slugify import slugify
from django.views import generic

from auth_app import models
from auth_app.models import UserProfile
from teams.models import TeamInvites
from .models import Translation, Roles, Invites, Game
from .utils.custom_paginator import CustomPaginator

User = get_user_model()
User: models.User


class HomeView(generic.ListView):
    template_name = 'translators_hub/home.html'
    context_object_name = 'latest_pages_list'
    paginate_by = 4
    paginator_class = CustomPaginator

    def __init__(self, *args, **kwargs):
        self.extra_filter = None
        super(HomeView, self).__init__(*args, **kwargs)

    def get_queryset(self):
        if self.extra_filter:
            return Translation.objects.filter(game__in=self.extra_filter.get('selected_game')).order_by(
                '-created_date')
        return Translation.objects.order_by('-created_date')

    def get(self, request, *args, **kwargs):
        selected_category = request.GET.get('game')
        games = Game.objects.all()
        selected_game = Game.objects.filter(game_name=selected_category) if selected_category is not None else None

        self.extra_filter = {
            'selected_game': selected_game if selected_game is not None else games
        }
        self.extra_context = {
            'games': games,
            'selected_game': selected_game
        }
        return super(HomeView, self).get(request, *args, **kwargs)


class SearchProjectView(generic.ListView):
    template_name = 'translators_hub/search_results.html'
    context_object_name = 'search_results'
    paginate_by = 5
    paginator_class = CustomPaginator

    def get_queryset(self):
        def add_model_name(obj):
            obj_name = obj._meta.model_name
            obj.model_name = obj_name
            return obj

        search_query = self.extra_context.get('search_query')
        if search_query:
            search_vector_for_projects = SearchVector('title', 'description')
            search_vector_for_users = SearchVector('user__username', 'user__first_name', 'user__last_name')
            searched_projects = Translation.objects.annotate(search=search_vector_for_projects).filter(
                search=search_query)
            searched_users = UserProfile.objects.annotate(search=search_vector_for_users).filter(
                search=search_query)
            search_results = list(map(add_model_name, list(searched_projects) + list(searched_users)))
            self.extra_context['total_objects'] = len(search_results)
            return search_results
        else:
            self.extra_context['search_query'] = ''
            search_results = list(
                map(add_model_name, list(Translation.objects.all()) + list(UserProfile.objects.all())))
            self.extra_context['total_objects'] = len(search_results)
            return search_results

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SearchProjectView, self).get_context_data(object_list=object_list, **kwargs)
        paginator: CustomPaginator = context['paginator']
        if not paginator.get_custom_immutable_href():
            name = 'search_query'
            value = self.extra_context.get('search_query')
            paginator.set_custom_immutable_href(href_name_value=((name, value),))
        return context

    def get(self, request, *args, **kwargs):
        search_query = request.GET.get('search_query')
        self.extra_context = {
            'search_query': search_query,
        }
        return super(SearchProjectView, self).get(request, *args, **kwargs)


# class DetailView(AddCommentMixin, generic.DetailView):
#     model = Translation
#     template_name = 'translators_hub/detail_page.html'
#     context_object_name = 'page_data'
#
#     def get(self, request, *args, **kwargs):
#         self.extra_context = {}
#         try:
#             self.get_comment_form()
#             if not isinstance(request.user, AnonymousUser):
#                 role_object = self.object.authors.get(user=request.user)
#                 if role_object.role in [Roles.ORGANISER, Roles.MODERATOR]:
#                     self.extra_context['moderator'] = True
#                     self.extra_context['delete_root'] = True
#             context = self.get_context_data(object=self.object)
#             return self.render_to_response(context)
#         except models.models.ObjectDoesNotExist:
#             return super(DetailView, self).get(request, *args, **kwargs)


# class ManagementView(generic.View):
#     template_name = 'translators_hub/project_management.html'
#
#     def get(self, request, slug, *args, **kwargs):
#         project = Translation.objects.get(slug=slug)
#         project_authors = None
#         project_moderator = None
#         description_form = ChangeDescriptionForm(instance=project)
#         if not isinstance(request.user, AnonymousUser):
#             project_authors = project.authors.order_by().prefetch_related('user', 'user__userprofile')
#             project_moderator = project.authors.filter(role__in=[Roles.ORGANISER, Roles.MODERATOR])
#         if project_moderator:
#             context = {
#                 'slug': slug,
#                 'user': request.user,
#                 'authors': project_authors,
#                 'form': description_form,
#             }
#             return render(request=request, template_name='translators_hub/project_management.html', context=context)
#         else:
#             error_message = "У вас недостаточно прав для захода на эту страницу"
#             messages.add_message(request=request, level=messages.ERROR, message=error_message)
#             context = {
#                 'current_page': project,
#             }
#             return render(request=request, template_name='translators_hub/detail_page.html', context=context)
#
#     def post(self, request, slug, *args, **kwargs):
#         project = Translation.objects.get(slug=slug)
#         if request.POST.get('fired'):
#             fired_users = Roles.objects.filter(user_id__in=request.POST.get('fired'))
#             for author in fired_users:
#                 project.authors.remove(author)
#                 project.save()
#             return redirect('translators_hub:management', slug=slug)
#         elif request.POST.get('save_description'):
#             change_description_form = ChangeDescriptionForm(request.POST, request.FILES, instance=project)
#             if change_description_form.is_valid():
#                 change_description_form.save()
#                 messages.add_message(request, level=messages.SUCCESS, message='Успешно!')
#             else:
#                 messages.add_message(request=request, level=messages.ERROR, message=change_description_form.errors)
#             return redirect('translators_hub:management', slug=slug, )
#         else:
#             return redirect('translators_hub:management', slug=slug)


# class ChangeRoleView(generic.edit.FormView):
#     form_class = ChangeUserRoleForm
#     template_name = 'translators_hub/change_user_role.html'
#     success_url = ''
#
#     def get(self, request, *args, **kwargs):
#         userprofile = User.objects.get(username=kwargs.get('username')).userprofile
#         self.extra_context = {'changing_user': kwargs.get('username'), 'userprofile': userprofile}
#         return super(ChangeRoleView, self).get(request, *args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         user = User.objects.get(username=kwargs.get('username'))
#         translation = Translation.objects.get(slug=kwargs.get('slug'))
#         old_role = user.roles.get(translation=translation)
#         new_role = Roles.objects.get_or_create(user=user, role=request.POST.get('role'))[0]
#         translation.authors.remove(old_role)
#         translation.authors.add(new_role)
#         return redirect('translators_hub:management', slug=kwargs.get('slug'))


# class ProfileView(AddCommentMixin, generic.DetailView):
#     template_name = 'translators_hub/profile_page.html'
#     context_object_name = 'page_data'
#
#     def get_queryset(self):
#         slug = self.request.resolver_match.kwargs.get('slug')
#         profile = UserProfile.objects.select_related().filter(slug=slug)
#         return profile
#
#     def get(self, request, *args, **kwargs):
#         slug = request.resolver_match.kwargs.get('slug')
#         self.get_comment_form()
#         if isinstance(request.user, AnonymousUser):
#             error_message = "Для просмотра профилей наших пользователей - авторизуйтесь!"
#             messages.add_message(request=request, level=messages.ERROR, message=error_message)
#             return redirect(request.META.get('HTTP_REFERER') if request.META.get('HTTP_REFERER') else reverse(
#                 'translators_hub:home'))
#         else:
#             self.extra_context = {
#                 'slug': slug,
#                 'delete_root': False
#             }
#             if request.user.userprofile.slug == slug:
#                 self.extra_context['update_button'] = True
#                 self.extra_context['delete_root'] = True
#             context = self.get_context_data(object=self.object)
#             return self.render_to_response(context)


# class UpdateProfileView(generic.UpdateView):
#     form_class = UpdateProfileForm
#     template_name = 'translators_hub/change_profile_info.html'

django_paradox_mode_translation/translators_hub/templates/translators_hub/add_page.html
{% extends 'translators_hub/base.html' %}

{% load static %}

{% block head %}
    <link type="text/css" href="{% static 'translators_hub/css/form_styles.css' %}" rel="stylesheet"/>
{% endblock head %}



{% block content %}
        <div class="container justify-content-center custom-div">
            <form action="{% url 'translators_hub:add_page' %}" method="post">
                {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="col text-center">
                        <table class="table table-light table-bordered">
                            {{ form }}
                        </table>
                        <button class="btn btn-success custom-button float-end" type="submit">Создать</button>
                    </div>
                </div>
            </form>
        </div>
{% endblock %}

django_paradox_mode_translation/translators_hub/templates/translators_hub/base.html
{% load translators_hub_tags %}
{% load chat_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link type="text/css" href="{% static 'translators_hub/css/messages_styles.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'translators_hub/css/icons styles.css' %}" rel="stylesheet">
    <title>Убежище переводчиков</title>
    {% block head %}

    {% endblock head %}
</head>

<body style="padding-top: 75px">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
<script src="{% static 'translators_hub/js/jQuery/jQuery.js' %}"></script>
<script src="{% static 'translators_hub/js/jsCookies/js.cookie.min.js' %}"></script>
{% block menu %}
    {% get_nav_bar %}
{% endblock %}
{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div{% if message.tags %} class="message {{ message.tags }} container"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endblock messages %}

{% block content %}

{% endblock content %}

{% block comments %}

{% endblock comments %}

{% block pagination %}

{% endblock pagination%}

{% block chat %}
    {% get_chats %}
{% endblock %}

</body>
</html>

django_paradox_mode_translation/translators_hub/templates/translators_hub/change_profile_info.html
{% extends 'translators_hub/base.html' %}


{% block content %}
    <div class="container justify-content-center">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form %}
                <table class="table table-light table-bordered">
                    {{ form }}
                </table>
                <p>Репутация: {{ profile_data.reputation }}</p>
                <button class="btn btn-success" type="submit">Сохранить</button>
                <button class="btn btn-warning" type="reset">Сбросить</button>
            {% endif %}
        </form>
    </div>
{% endblock %}

django_paradox_mode_translation/translators_hub/templates/translators_hub/change_user_role.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    <div class="container-sm">
        <table class="table table-light table-bordered">
            <tr>
                <th><label>Никнейм:</label></th>
                <td>
                    <div class="">{{ changing_user }}</div>
                </td>

            </tr>
            <tr>
                <th><label>Опыт:</label></th>
                <td>
                    <div>{{ userprofile.experience }}</div>
                </td>
            </tr>
        </table>
    </div>
    <div class="container-sm">
    <form method="post">
        {% csrf_token %}
        <table class="table table-light">{{ form }}</table>
        <button class="btn btn-success" type="submit">Принять</button>
    </form>
    </div>
{% endblock content %}

django_paradox_mode_translation/translators_hub/templates/translators_hub/comments_block.html
{% load static %}
{% load translators_hub_tags %}
{% load translators_hub_filters %}


<div class="container border-3 justify-content-center">
    {% if comment_form %}
        <form method="post" class="p-3">
            {% csrf_token %}
            <table class="table table-borderless">
                {{ comment_form }}
            </table>
            <div class="container text text-end">
                <button class="btn btn-success" type="submit">Отправить</button>
            </div>
        </form>
    {% endif %}

    {% get_comments page_data as page_obj %}
    {% if page_obj %}
        <ul class="list-group">
            {% for comment in page_obj.object_list %}
                <li class="list-group-item">
                    <div class="row">
                        <div class="comment-container col"
                             style="background-color: #eee; padding: 10px; margin-bottom: 10px; position: relative;">
                            <div class="author-date-container"
                                 style="display: flex; justify-content: space-between; align-items: center;">
                                <a style="margin: 0;"
                                   href="{{ comment.author.get_absolute_url }}"><strong>{{ comment.author }}</strong></a>
                                <p style="margin: 0; color: #888;">{{ comment.pub_date }}</p>
                            </div>

                            <p style="margin: 10px 0; padding-right: 60px;">{{ comment.comment_text }}</p>

                            <div class="comment-buttons"
                                 style="position: absolute; bottom: 5px; right: 5px; display: flex; gap: 5px;">
                                <div>
                                    <span data-page="{{ page_data|get_model_name }}" data-url="{% url 'translators_hub:like-comment' %}"
                                          id="likes-comment-{{ comment.pk }}">{{ comment.likes }}</span>
                                    <button id="like-button-{{ comment.pk }}" type="button" class="btn {{ comment.like_class }} btn-sm rounded-circle"
                                            onclick="likeComment({{ comment.pk }})">👍
                                    </button>
                                </div>
                                <div>
                                    <span data-page="{{ page_data|get_model_name }}" data-url="{% url 'translators_hub:dislike-comment' %}"
                                          id="dislikes-comment-{{ comment.pk }}">{{ comment.dislikes }}</span>
                                    <button id="dislike-button-{{ comment.pk }}" type="button" class="btn {{ comment.dislike_class }} btn-sm rounded-circle"
                                            onclick="dislikeComment({{ comment.pk }})">👎
                                    </button>
                                </div>
                            </div>
                        </div>
                        {% if delete_root %}
                            <div class="col-auto text-end">
                                <form method="post" name="delete">
                                    {% csrf_token %}
                                    <input class="button" type="hidden" name="comment_id"
                                           value="{{ comment.pk }}">
                                    <button type="submit" class="btn btn-danger btn-sm rounded-circle">
                                        🗑️
                                    </button>
                                </form>
                            </div>
                        {% endif %}
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% get_pagination_block page_obj %}
    {% endif %}
</div>

django_paradox_mode_translation/translators_hub/templates/translators_hub/invites.html
{% extends 'translators_hub/base.html' %}
{% load translators_hub_tags %}

{% block content %}
    {% if errors %}
        {% for error in errors %}
            <p>error</p>
        {% endfor %}
    {% endif %}
    <h1 class="modal-title">Приглашения для вас:</h1>
    {% if invites %}
        <div class="container">
            <table class="table table-light table-hover table-bordered">
                <tr>
                    <td>Перевод мода</td>
                    <td>Автор</td>
                    <td>Приглашение</td>
                    <td>Должность</td>
                </tr>
                {% for invite in invites %}
                    <tr>
                        <td><a class="btn btn-outline-info"
                               href="{{ invite.mod_translation.get_absolute_url }}">{{ invite.mod_translation }}</a>
                        </td>
                        <td>{{ invite.sender }}</td>
                        <td>{{ invite.text_invite }}</td>
                        <td>{% get_role_display role=invite.role %}</td>
                        <td>
                            <form method="post" action="{% url 'translators_hub:invites' slug %}">{% csrf_token %}
                                <button class="btn btn-outline-success" type="submit" value="{{ invite.pk }}"
                                        name="accept">Принять
                                </button>
                                |
                                <button class="btn btn-outline-danger" type="submit" value="{{ invite.pk }}"
                                        name="decline">Отклонить
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <h3>Пока для вас ничего нет</h3>
    {% endif %}
    <hr>
    <h1 class="modal-title">Приглашения в команды для вас:</h1>
    {% if team_invites %}
        <div class="container">
            <table class="table table-light table-hover table-bordered">
                <tr>
                    <td>Команда</td>
                    <td>Глава команды</td>
                    <td>Приглашение</td>
                </tr>
                {% for invite in team_invites %}
                    <tr>
                        <td><a class="btn btn-outline-info"
                               href="{{ invite.team.get_absolute_url }}">{{ invite.team }}</a>
                        </td>
                        <td>{{ invite.sender }}</td>
                        <td>{{ invite.text_invite }}</td>
                        <td>
                            <form method="post" action="{% url 'teams:invites'%}">{% csrf_token %}
                                <button class="btn btn-outline-success" type="submit" value="{{ invite.pk }}"
                                        name="accept">Принять
                                </button>
                                |
                                <button class="btn btn-outline-danger" type="submit" value="{{ invite.pk }}"
                                        name="decline">Отклонить
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <h3>Пока для вас ничего нет</h3>
    {% endif %}
{% endblock content %}

django_paradox_mode_translation/translators_hub/templates/translators_hub/login.html
{% extends 'translators_hub/base.html' %}
{% load static %}

{% block head %}
    <link type="text/css" href="{% static 'translators_hub/css/form_styles.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
    <div class="container">
        <form action="{% url 'translators_hub:login' %}" method="post">
            {% csrf_token %}
            <table class="table table-light">
                {{ form }}
            </table>
            <button class="btn btn-dark" type="submit">Войти</button>
        </form>
    </div>
{% endblock content %}

django_paradox_mode_translation/translators_hub/templates/translators_hub/my_projects.html
{% extends 'translators_hub/base.html' %}
{% load translators_hub_tags %}
{% load static %}

{% block head %}
    <link type="text/css" href="{% static 'translators_hub/css/list_styles.css' %}" rel="stylesheet">
{% endblock head %}


{% block content %}
    <div class="container">
    <table class="table table-bordered table-light table-hover">
        <tr>
            <td>Название</td>
            <td>Должность</td>
            <td>Игра</td>
            <td>Количество участников</td>
            <td>Количество просмотров</td>
        </tr>
        {% for project in projects_list %}
            <tr>
                <td><a class="btn btn-secondary" href="{% url 'translators_hub:detail_page' slug=project.slug %}">{{ project.title | truncatechars:50 }}</a></td>
                <td>{{ project.role }}</td>
                <td>{{ project.game }}</td>
                <td class="td-number">{{ project.authors.all | length}}</td>
                <td class="td-number">{{ project.views }}</td>
            </tr>
        {% endfor %}
    </table>
    </div>
{% endblock content %}

django_paradox_mode_translation/translators_hub/templates/translators_hub/nav-bar.html
{% load static %}

<nav class="navbar fixed-top navbar-dark bg-dark" aria-label="Dark offcanvas navbar">
    <div class="container-fluid">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a class="navbar-brand" href="{% url 'translators_hub:home' %}"><img style="max-height: 50px; max-width: 50px"
                    class="img-thumbnail rounded-circle"
                    src="{% static 'translators_hub/images/main icon.jpg' %}" alt="Лого сайта"></a>
            <a class="navbar-brand" href="{% url 'translators_hub:add_page' %}">Добавить страницу</a>
            <a class="navbar-brand" href="{% url 'teams:home' %}">Команды</a>
            <a class="navbar-brand" href="{% url 'moderators:home' %}">Модерация сайта</a>

        </div>
    <div class="row">
        <div class="col">
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 navbar-toggler" action="{% url 'translators_hub:search' %}">
            <input name="search_query" type="search" class="form-control form-control-dark" placeholder="Поиск..." aria-label="Search">
        </form>
        </div>
        <div class="col-auto">
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark"
                aria-controls="offcanvasNavbarDark">
            {{ button_name }}
        </button>
        </div>
    </div>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbarDark"
             aria-labelledby="offcanvasNavbarDarkLabel">
            <div class="offcanvas-header">
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body" style="font-size: 20px">
            <input type="hidden" id="user-logged" value="{{ user }}">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    {% if user_logged %}
                        <li><a class="dropdown-item"
                               href="{% url 'translators_hub:profile' user_logged.slug %}"><img src="/media/{{ user_logged.profile_image }}" alt="{{ user_logged.profile_image }}" class="profile-icon">Профиль</a></li>

                        <li><a id="active-projects" class="dropdown-item"
                               href="{% url 'translators_hub:my_projects' user_logged.slug %}">Мои
                            проекты({{ active_projects|length }})</a></li>
                        <li><a id="active-invites" class="dropdown-item"
                               href="{% url 'translators_hub:invites' user_logged.slug %}">Приглашения
                            ({{ active_invites|length }} | {{ active_team_invites|length }})</a>
                        </li>
                        <li>
                            <a class="btn btn-danger"
                               href="{% url 'translators_hub:logout' %}">{{ registration_status }}</a>

                        </li>

                    {% else %}
                        <li><a class="dropdown-item"
                               href="{% url 'translators_hub:login' %}">{{ login_status }}</a></li>
                        <li><a class="dropdown-item"
                               href="{% url 'translators_hub:registration' %}">{{ registration_status }}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>

<script src="{% static 'translators_hub/js/userWebSocket.js' %}"></script>