django_paradox_mode_translation/chats/urls.py
from django.urls import path

from chats.views import SendMessageView

app_name = 'chats'

urlpatterns = [
    path('<slug:slug>/', SendMessageView.as_view(), name='send_message')
]

django_paradox_mode_translation/django_paradox_mode_translation/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django_paradox_mode_translation import settings

urlpatterns = [
    path('', include('translators_hub.urls'), name='home'),
    path('teams/', include('teams.urls'), name='teams'),
    path('moderators/', include('moderators.urls'), name='moderators'),
    path('chats/', include('chats.urls'), name='chats'),
    path('admin/', admin.site.urls),

]

if settings.DEBUG is True:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

django_paradox_mode_translation/moderators/urls.py
from django.urls import path

from moderators.views import ModeratorHomeView, SendQueryView, MyQueriesView, QueryBookingView, QueriesInWorkView, \
    QueryDetailView, AddGameView

app_name = 'moderators'

urlpatterns = [
    path('', ModeratorHomeView.as_view(), name='home'),
    path('send-query/', SendQueryView.as_view(), name='send_query'),
    path('my-queries/', MyQueriesView.as_view(), name='my_queries'),
    path('query-booking/', QueryBookingView.as_view(), name='query_booking'),
    path('queries-in-work/', QueriesInWorkView.as_view(), name='queries_in_work'),
    path('query<int:pk>', QueryDetailView.as_view(), name='query_detail'),
    path('add-game/', AddGameView.as_view(), name='add_game'),
]

django_paradox_mode_translation/moderators/models.py
from django.db import models


class Query(models.Model):

    NO_MODERATOR = None
    IN_WORK = 'w'
    COMPLETE = 'c'
    DENIED = 'd'

    STATUS = [
        (NO_MODERATOR, "Нет исполнителя"),
        (IN_WORK, "В работе"),
        (COMPLETE, "Выполнено"),
        (DENIED, "В запросе отказано")
    ]

    query_text = models.CharField(
        max_length=4500,
        blank=False,
        null=False,
        verbose_name="Текст заявки"
    )

    topic = models.ForeignKey(
        to='Topic',
        on_delete=models.PROTECT,
        related_name='topic_queries'
    )

    query_author = models.ForeignKey(
        to='auth_app.User',
        on_delete=models.SET_NULL,
        related_name="user_queries",
        default=None,
        null=True,
        verbose_name="Автор заявки"
    )

    pub_date = models.DateTimeField(
        verbose_name="Заявка опубликована",
        null=False,
        auto_now_add=True
    )

    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default=None,
        null=True,
        verbose_name="Статус заявки"
    )

    query_considered = models.ForeignKey(
        to='auth_app.User',
        on_delete=models.SET_NULL,
        related_name='queries_in_work',
        null=True,
        default=None,
        verbose_name="Модератор, принявший заявку"
    )

    denial_reason = models.CharField(
        max_length=1000,
        blank=True,
        default=None,
        null=True,
        verbose_name="Причина отказа"
    )

    accept_date = models.DateTimeField(
        verbose_name="Заявка принята к рассмотрению",
        blank=True,
        default=None,
        null=True,
    )

    complete_date = models.DateTimeField(
        verbose_name="Заявка рассмотрена",
        blank=True,
        default=None,
        null=True,
    )

    def __str__(self):
        return f'Заявка №{self.pk}'

    class Meta:
        verbose_name = "Обращение"
        verbose_name_plural = "Обращения"


class Topic(models.Model):

    topic_title = models.CharField(
        max_length=120,
        blank=False,
        unique=True,
        verbose_name="Тема обращения"
    )

    def __str__(self):
        return f'Тема - {self.topic_title}'

    class Meta:
        verbose_name = "Тема обращения"
        verbose_name_plural = "Темы обращений"

django_paradox_mode_translation/moderators/forms.py
from django import forms

from moderators.models import Query, Topic
from translators_hub.models import Game


class SendQueryForm(forms.ModelForm):

    query_text = forms.CharField(
        widget=forms.Textarea(attrs={

        }),
        required=True,
        label="Текст заявки"
    )

    topic = forms.ModelChoiceField(
        widget=forms.Select(attrs={

        }),
        queryset=Topic.objects.filter(),
        label="Тема заявки"
    )

    class Meta:
        model = Query
        fields = ['query_text', 'topic']


class QueryDenialForm(forms.ModelForm):

    denial_reason = forms.CharField(
        widget=forms.Textarea(attrs={

        }),
        required=True,
        label="Основания для отказа"
    )

    class Meta:
        model = Query
        fields = ['denial_reason']


class AddGameForm(forms.ModelForm):

    game_name = forms.CharField(
        widget=forms.TextInput(attrs={

        }),
        required=True,
        label="Название игры"
    )

    description = forms.CharField(
        widget=forms.Textarea(attrs={

        }),
        required=False,
        label="Описание"
    )

    class Meta:
        model = Game
        fields = ['game_name', 'description']

django_paradox_mode_translation/moderators/views.py
import django.utils.timezone
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from django.views import View
from django.views.generic import FormView, ListView, DetailView
from django.views.generic.edit import FormMixin

from moderators.forms import SendQueryForm, QueryDenialForm, AddGameForm
from moderators.models import Query
from translators_hub.utils.custom_paginator import CustomPaginator


class ModeratorHomeView(View):

    def get(self, request, *args, **kwargs):
        return render(request=request, template_name='moderators/home.html')


class SendQueryView(FormView):
    template_name = 'moderators/send_query.html'
    form_class = SendQueryForm
    success_url = reverse_lazy('moderators:home')

    def get(self, request, *args, **kwargs):
        return super(SendQueryView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super(SendQueryView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.query_author = self.request.user
        form.instance.status = None
        form.save()
        return super(SendQueryView, self).form_valid(form)


class MyQueriesView(ListView):
    model = Query
    paginator_class = CustomPaginator
    paginate_by = 10
    context_object_name = 'queries'
    template_name = 'moderators/my_queries.html'

    def get_queryset(self):
        my_queries = Query.objects.filter(query_author=self.request.user).select_related('query_considered',
                                                                                         'query_considered__userprofile',
                                                                                         'topic')
        return my_queries


class QueryBookingView(ListView):
    model = Query
    paginator_class = CustomPaginator
    paginate_by = 10
    context_object_name = 'queries'
    template_name = 'moderators/query_booking.html'

    def get_queryset(self):
        queries = Query.objects.filter(status=None).select_related('query_author', 'query_author__userprofile',
                                                                   'topic').order_by('pub_date')
        return queries

    def post(self, request, *args, **kwargs):
        query = Query.objects.get(pk=request.POST.get('query_pk'))
        query.query_considered = request.user
        query.status = Query.IN_WORK
        query.accept_date = django.utils.timezone.now()
        query.save()
        return redirect(reverse('moderators:query_booking'))


class QueriesInWorkView(ListView):
    model = Query
    paginator_class = CustomPaginator
    paginate_by = 10
    context_object_name = 'queries'
    template_name = 'moderators/queries_in_work.html'

    def get_queryset(self):
        queries = Query.objects.filter(query_considered=self.request.user, status=Query.IN_WORK).select_related(
            'query_author',
            'query_author__userprofile',
            'topic').order_by(
            'accept_date')
        return queries


class QueryDetailView(FormMixin, DetailView):
    context_object_name = 'query'
    model = Query
    form_class = QueryDenialForm
    success_url = reverse_lazy('moderators:queries_in_work')

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        query = Query.objects.filter(pk=pk).select_related('query_author', 'query_considered')
        return query.get()

    def get(self, request, *args, **kwargs):
        super_method = super(QueryDetailView, self).get(request, *args, **kwargs)
        if request.user == self.object.query_considered:
            return super_method
        else:
            error_text = "Для доступа к этой страницы вы должны быть назначены исполнителем данной заявки"
            messages.add_message(request=request, level=messages.ERROR, message=error_text)
            return redirect(self.success_url)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if request.POST.get('decision'):
            query = self.object
            query.status = Query.COMPLETE
            query.complete_date = django.utils.timezone.now()
            query.save()
            return redirect(self.success_url)
        else:
            form = self.get_form()
            form.instance.status = Query.DENIED
            form.instance.complete_date = django.utils.timezone.now()
            if form.is_valid():
                form.save()
                return self.form_valid(form)
            else:
                return self.form_invalid(form)

    def get_form_kwargs(self):
        kwargs = super(QueryDetailView, self).get_form_kwargs()
        kwargs['instance'] = self.object
        return kwargs


class AddGameView(FormView):
    form_class = AddGameForm
    template_name = 'moderators/add_game.html'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.save()
            return redirect('moderators:queries_in_work')
        else:
            return self.form_invalid(form)

django_paradox_mode_translation/moderators/templates/moderators/add_game.html
{% extends 'translators_hub/base.html' %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Добавить игру</button>
    </form>

{% endblock %}

django_paradox_mode_translation/moderators/templates/moderators/home.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    <a href="{% url 'moderators:send_query' %}">Отправить заявку</a>
    <a href="{% url 'moderators:my_queries' %}">Оставленные заявки</a>
    <a href="{% url 'moderators:query_booking' %}">Рассмотреть заявки</a>
    <a href="{% url 'moderators:queries_in_work' %}">Заявки на рассмотрении</a>
{% endblock %}

django_paradox_mode_translation/moderators/templates/moderators/my_queries.html
{% extends 'translators_hub/base.html' %}
{% load translators_hub_tags %}

{% block content %}
    <table class="table table-hover table-bordered">
        <tr>
            <th>Номер заявки</th>
            <th>Текст обращения</th>
            <th>Тема обращения</th>
            <th>Статус заявки</th>
            <th>Заявка отправлена</th>
            <th>Модератор, начавший рассмотрение</th>
            <th>Начало рассмотрения</th>
            <th>Заявка рассмотрена</th>
            <th>Основания для отказа</th>
        </tr>
        {% for query in queries %}
            <tr>
                <td>{{ query.pk }}</td>
                <td>{{ query.query_text }}</td>
                <td>{{ query.topic }}</td>
                <td>{{ query.get_status_display }}</td>
                <td>{{ query.pub_date }}</td>
                <td>{% if query.query_considered %}<a href="{{ query.query_considered.get_absolute_url }}">{{ query.query_considered }}</a>{% else %}Не назначен{% endif %}</td>
                <td>{% if query.accept_date %}{{ query.accept_date }}{% else %}{% endif %}</td>
                <td>{% if query.complete_date %}{{ query.complete_date }}{% else %}{% endif %}</td>
                <td>{% if query.denial_reason %}{{ query.denial_reason }}{% else %}{% endif %}</td>
            </tr>
        {% endfor %}


    </table>
{% endblock %}

{% block pagination %}
    {% get_pagination_block page_obj %}
{% endblock %}

django_paradox_mode_translation/moderators/templates/moderators/queries_in_work.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    <table class="table table-hover table-bordered">
        <tr>
            <th>Заявка №</th>
            <th>Автор заявки</th>
            <th>Текст заявки</th>
            <th>Тема заявки</th>
            <th>Дата размещения заявки</th>
            <th>Начало рассмотрения</th>
        </tr>
        {% for query in queries %}
            <tr>
                <td>{{ query.pk }}</td>
                <td>{{ query.query_text }}</td>
                <td><a href="{{ query.query_author.get_absolute_url }}">{{ query.query_author }}</a></td>
                <td>{{ query.topic }}</td>
                <td>{{ query.pub_date }}</td>
                <td>{{ query.accept_date }}</td>
                <td>
                    <a href="{% url 'moderators:query_detail' pk=query.pk %}">Принять решение</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

django_paradox_mode_translation/moderators/templates/moderators/query_booking.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    <table class="table table-bordered table-hover">
        <tr>
            <th>Заявка №</th>
            <th>Текст заявки</th>
            <th>Автор заявки</th>
            <th>Тема заявки</th>
        </tr>
        {% for query in queries %}
            <tr>
                <td>{{ query.pk }}</td>
                <td>{{ query.query_text }}</td>
                <td>{{ query.query_author }}</td>
                <td>{{ query.topic }}</td>
                <td>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="query_pk" value="{{ query.pk }}">
                        <button type="submit">Рассмотреть</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

django_paradox_mode_translation/moderators/templates/moderators/query_detail.html
{% extends 'translators_hub/base.html' %}

{% block content %}
    {{ query.query_text }}
    {{ query.query_author }}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Отказать</button>
    </form>

    <form method="post">
        {% csrf_token %}
        <button name="decision" value="Accept" type="submit">Принять</button>
    </form>


    <a href="{% url 'moderators:add_game' %}">Добавить игру</a>
{% endblock %}

django_paradox_mode_translation/moderators/templates/moderators/send_query.html
{% extends 'translators_hub/base.html' %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Отправить запрос</button>
    </form>
{% endblock %}